name: "decoder"
backend: "tensorrt"
max_batch_size: 0

input [
    { name: "ASR",   data_type: TYPE_FP32, dims: [ -1, 512, -1 ] },
    { name: "F0_OUT",   data_type: TYPE_FP32, dims: [ -1, 1, -1 ] },
    { name: "N_OUT",   data_type: TYPE_FP32, dims: [ -1, 1, -1 ] },
    { name: "REF",   data_type: TYPE_FP32, dims: [ -1, 128 ] }
]

output [
    { name: "X_OUT",   data_type: TYPE_FP32, dims: [ -1, 512, -1 ] }
]

instance_group [ { kind: KIND_GPU, count: 1} ]

