#!/usr/bin/env python3
"""Generate one export config per model from the legacy speaker JSON files.

``speaker_configs.json`` holds each speaker's S3 keys; ``speaker_languages.json``
groups speakers by language and names the model each one belongs to. Speakers
that share a model share its checkpoint, so they become one config file with
several entries under ``speakers:``.

    python tools/generate_configs.py --out configs/generated

This is a migration aid, not part of the export path. Once the generated files
are reviewed, they are the source of truth and the JSONs can go.
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# PLBERT variant per language. The multilingual checkpoint covers the Latin and
# Cyrillic scripts; Indic languages use their own. Verify against the contents
# of the PLBERTs/ prefix before trusting these for a new language.
INDIC = {"hi", "te", "ta", "bn", "mr", "kn", "pa", "gu", "ml"}


def plbert_for(languages: set) -> str:
    return "PLBERTs/multi_indic" if languages and languages <= INDIC else "PLBERTs/multi"


HEADER = """\
# Generated by tools/generate_configs.py from speaker_configs.json +
# speaker_languages.json. Review before use -- in particular `plbert`, which is
# inferred from the speakers' languages.
#
#   python convert.py {config} --dry-run
"""


def render(model_id: str, speakers: dict, languages: dict, plbert: str, checkpoint: dict) -> str:
    lines = [HEADER.format(config=f"configs/generated/{model_id}.yaml"), ""]
    lines.append(f"model_id: {model_id}")
    lines.append("")
    lines.append("stores:")
    lines.append("  prod:")
    lines.append("    type: s3")
    lines.append("    bucket: verizon-audio-main")
    lines.append("    access_key_env: AWS_ACCESS_KEY")
    lines.append("    secret_key_env: AWS_SECRET_KEY")
    lines.append("  b2:")
    lines.append("    type: s3")
    lines.append("    bucket: TTS-STT-servers")
    lines.append("    endpoint_url: https://s3.us-east-005.backblazeb2.com")
    lines.append("    access_key_env: B2_KEY_ID")
    lines.append("    secret_key_env: B2_APP_KEY")
    lines.append("")
    lines.append("defaults:")
    lines.append("  store: prod")
    lines.append("")
    lines.append("checkpoint:")
    lines.append(f"  model: {checkpoint['model']}")
    lines.append(f"  config: {checkpoint['config']}")
    lines.append("")
    lines.append("plbert:")
    lines.append("  store: b2")
    lines.append(f"  path: {plbert}")
    lines.append("")
    lines.append("speakers:")
    for name in sorted(speakers):
        lines.append(f"  {name}:")
        lines.append(f"    reference: {speakers[name]}")
        speaker_languages = sorted(languages.get(name, []))
        if len(speaker_languages) == 1:
            lines.append(f"    language: {speaker_languages[0]}")
        elif speaker_languages:
            lines.append(f"    languages: [{', '.join(speaker_languages)}]")
    lines.append("")
    lines.append("export:")
    lines.append("  device: cuda:0")
    lines.append("  opset: 17")
    lines.append("  modules: all")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--speaker-configs", default=str(REPO_ROOT / "config" / "json_files" / "speaker_configs.json"))
    parser.add_argument("--speaker-languages", default=str(REPO_ROOT / "config" / "json_files" / "speaker_languages.json"))
    parser.add_argument("--out", default=str(REPO_ROOT / "configs" / "generated"))
    args = parser.parse_args()

    speaker_configs = json.loads(Path(args.speaker_configs).read_text())
    speaker_languages = json.loads(Path(args.speaker_languages).read_text())

    # A multilingual voice appears under several languages with the same
    # model, so collect every language rather than keeping the last one seen.
    model_of = {}
    languages_of = defaultdict(list)
    for language, speakers in speaker_languages.items():
        for speaker, model_id in speakers.items():
            previous = model_of.setdefault(speaker, model_id)
            if previous != model_id:
                raise SystemExit(
                    f"speaker '{speaker}' maps to both '{previous}' and "
                    f"'{model_id}' in speaker_languages.json"
                )
            languages_of[speaker].append(language)

    groups = defaultdict(dict)
    languages_by_model = defaultdict(set)
    checkpoints = {}
    orphans = []

    for speaker, entry in speaker_configs.items():
        if speaker not in model_of:
            orphans.append(speaker)
            continue
        model_id = model_of[speaker]
        groups[model_id][speaker] = entry["reference"]
        languages_by_model[model_id].update(languages_of[speaker])

        candidate = {"model": entry["model"], "config": entry["config"]}
        if model_id in checkpoints and checkpoints[model_id] != candidate:
            raise SystemExit(
                f"model '{model_id}' has conflicting checkpoints:\n"
                f"  {checkpoints[model_id]}\n  {candidate}  (from speaker '{speaker}')"
            )
        checkpoints[model_id] = candidate

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    for model_id in sorted(groups):
        text = render(
            model_id,
            groups[model_id],
            languages_of,
            plbert_for(languages_by_model[model_id]),
            checkpoints[model_id],
        )
        (out_dir / f"{model_id}.yaml").write_text(text)

    print(f"wrote {len(groups)} config(s) to {out_dir}")
    for model_id in sorted(groups):
        langs = ",".join(sorted(languages_by_model[model_id]))
        print(f"  {model_id:<24} {len(groups[model_id]):>2} speaker(s)  [{langs}]")
    if orphans:
        print(f"\nskipped (not in speaker_languages.json): {sorted(orphans)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
